"""add_hubspot_connections_table

Revision ID: 0cd01d66c010
Revises: f22d92ce7ea7
Create Date: 2026-09-03 11:39:58.434805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd01d66c010'
down_revision: Union[str, Sequence[str], None] = 'f22d92ce7ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubspot_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('data_hosting_location', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hubspot_connections_portal_id'), 'hubspot_connections', ['portal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hubspot_connections_portal_id'), table_name='hubspot_connections')
    op.drop_table('hubspot_connections')
    # ### end Alembic commands ###
