"""Initial schema

Revision ID: 562dbb059b0e
Revises: 
Create Date: 2026-08-06 12:20:49.629200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562dbb059b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=True),
    sa.Column('is_dm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('rss_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('last_polled', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_feeds_url'), 'rss_feeds', ['url'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('onboarding_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rss_history',
    sa.Column('entry_id', sa.String(length=512), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('rss_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.String(length=255), nullable=False),
    sa.Column('subscriber_type', sa.String(length=50), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('companies', sa.JSON(), nullable=True),
    sa.Column('geographies', sa.JSON(), nullable=True),
    sa.Column('representatives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('parameter_1', sa.Integer(), nullable=True),
    sa.Column('parameter_2', sa.Integer(), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_subscriptions_ticker'), 'stock_subscriptions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_subscriptions_ticker'), table_name='stock_subscriptions')
    op.drop_table('stock_subscriptions')
    op.drop_table('rss_subscriptions')
    op.drop_table('rss_history')
    op.drop_table('users')
    op.drop_index(op.f('ix_rss_feeds_url'), table_name='rss_feeds')
    op.drop_table('rss_feeds')
    op.drop_table('rooms')
    # ### end Alembic commands ###
