from datetime import datetime
from sqlalchemy import String, Boolean, DateTime, func, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from src.models.base import Base

class User(Base):
    """Represents a bot user, tracking lead details, onboarding progress, and licensing tiers."""
    __tablename__ = "users"

    user_id: Mapped[str] = mapped_column(String(255), primary_key=True)  # Matrix User ID (e.g. @user:matrix.org)
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    company: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    consent_given: Mapped[bool] = mapped_column(Boolean, default=False)
    tier: Mapped[str] = mapped_column(String(50), default="FREE")  # 'FREE' or 'PREMIUM'
    
    # Onboarding state machine: PENDING, ASKED_NAME, ASKED_COMPANY, ASKED_EMAIL, COMPLETED
    onboarding_state: Mapped[str] = mapped_column(String(50), default="PENDING")
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now())

    def __repr__(self) -> str:
        return f"<User user_id={self.user_id} tier={self.tier} state={self.onboarding_state}>"


class LicenseCode(Base):
    """Represents premium activation codes generated by administrators."""
    __tablename__ = "license_codes"

    code: Mapped[str] = mapped_column(String(255), primary_key=True)
    is_used: Mapped[bool] = mapped_column(Boolean, default=False)
    used_by: Mapped[str | None] = mapped_column(String(255), ForeignKey("users.user_id", ondelete="SET NULL"), nullable=True)
    used_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now())

    def __repr__(self) -> str:
        return f"<LicenseCode code={self.code} is_used={self.is_used}>"
